name: Commit Lint

on:
  workflow_call:

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          PATTERN="^(main$|v[0-9].*$|(feature|bugfix|hotfix|enhancement|release|refactor|ci|style|docs|chore)\/.*$)"
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"

          if [[ ! $BRANCH_NAME =~ $PATTERN ]]; then
            echo "❌ Error: branch name '$BRANCH_NAME' non-compliant with regulations!"
            exit 1
          fi
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24.0"

      - name: Checkout Commit Lint Scripts
        uses: actions/checkout@v5
        with:
          repository: kuro-helper/.github
          path: common-workflow-project

      - name: Run Commit Lint Script
        run: go run common-workflow-project/scripts/check_commit.go
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_HEAD_REF: ${{ github.event.pull_request.head.ref || '' }}
