name: Go Build

on:
  workflow_call:
    inputs:
      use_kurohelpercore:
        type: string
        default: ''
      use_kurohelperdb:
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: main

      - name: Checkout kurohelper-core
        if: ${{ inputs.use_kurohelpercore != '' }} 
        uses: actions/checkout@v5
        with:
          repository: kuro-helper/kurohelper-core
          ref: ${{ inputs.use_kurohelpercore }}
          path: kurohelpercore

      - name: Checkout kurohelper-db
        if: ${{ inputs.use_kurohelperdb != '' }} 
        uses: actions/checkout@v5
        with:
          repository: kuro-helper/kurohelper-db
          ref: ${{ inputs.use_kurohelperdb }}
          path: kurohelperdb

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24.0"
          cache-dependency-path: main/go.sum

      - name: Link Local Dependencies
        run: |
            cd main
            if [ -d "../kurohelpercore" ]; then
              echo "Linking kurohelper-core to ../kurohelpercore"
              go mod edit -replace kurohelper-core=../kurohelpercore
            fi
            
            if [ -d "../kurohelperdb" ]; then
              echo "Linking kurohelper-db to ../kurohelperdb"
              go mod edit -replace kurohelper-db=../kurohelperdb
            fi
            
            echo "Updated go.mod content:"
            cat go.mod

      - name: Build
        run: |
          cd main
          go build -v ./...

      # - name: Test
      #   run: go test -v ./...